CHANGELOGにJakartaEE由来の文言修正の内容追記
nablarch-development-standards/nablarch-development-standards-tools pull request #17
Opened 2024-06-21 07:47 UTC by tisuchida

2024-06-21 09:30 UTC, kumagoro1202 approved these changes

2024-06-21 09:34 UTC, kumagoro1202 requested changes

2024-06-21 09:34 UTC, kumagoro1202 commented on CHANGELOG.md
> +- Nablarch6系で業務画面JSP検証ツールが削除されたことに伴い、記載を削除しました。
ここでJSP使っちゃうとまたJakarta EEの名称じゃなくなってしまうので
「Nablarch6系でJSP静的解析ツールはJakarta Server Pages静的解析ツールに名称変更となったため」とかにして欲しい。
業務画面JSP検証ツールは古いものだからそのままでいいです。
JSPとJakarta Server Pagesを同じページに書くことで最低限の保険にはなるかと思います。

2024-06-23 23:57 UTC, tisuchida commented on CHANGELOG.md
> +- Nablarch6系で業務画面JSP検証ツールが削除されたことに伴い、記載を削除しました。
文言をJakarta Server Pagesを含む形に修正しました。
b634fca9a13ee9eb2c57bfeada5a1479f62c9f3f

2024-06-24 00:21 UTC, kumagoro1202 approved these changes

2024-06-24 00:21 UTC, merged